# .github/workflows/cdk.yml
name: CDK Build and Deploy

on:
  workflow_call:

jobs:
  build-and-deploy:
    name: CDK Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      
      - name: Print the Docker Hub username (masked)
        run: echo "Docker Hub Username ${{ secrets.DOCKERHUB_USERNAME }}"
        

      

