# .github/workflows/development.yml
name: Production
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy-to-development:
    uses: ./.github/workflows/cdk.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            
