# .github/workflows/development.yml
name: Production
on:
  workflow_dispatch: {}
  push:
    branches:
      - sathish
jobs:
  deploy-to-development:
    uses: ./.github/workflows/cdk.yml
    with:
      PROJECT_ENVIRONMENT: production
      AWS_REGION: ap-south-1
      PROJECT_NAME: tecofize
      GIT_HASH: ${{ github.sha }}
            
